version: '3.7'

services:
  postgres:
    container_name: "source_postgres"
    image: postgres:17-alpine
    restart: always
    env_file:
      - db/postgres/env/.postgres.env
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
      - pg-conf:/etc/postgresql
      - pg-log:/var/log/postgresql

volumes:
  pg-data:
    driver: local
  pg-conf:
    driver: local
  pg-log:
    driver: local
