"""Initial

Revision ID: 9b3f3de3a204
Revises: 
Create Date: 2024-11-30 18:11:09.089686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b3f3de3a204'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('description_graduates_university',
    sa.Column('object_level', sa.String(length=6), nullable=False),
    sa.Column('object_name', sa.String(length=64), nullable=False),
    sa.Column('gender', sa.String(length=7), nullable=False),
    sa.Column('education_level', sa.String(length=64), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('university', sa.String(length=256), nullable=False),
    sa.Column('special_section', sa.String(length=256), nullable=False),
    sa.Column('speciality', sa.String(length=256), nullable=False),
    sa.Column('speciality_code', sa.String(length=8), nullable=False),
    sa.Column('count_graduate', sa.Integer(), nullable=False),
    sa.Column('percent_employed', sa.Float(), nullable=False),
    sa.Column('average_salary', sa.Float(), nullable=True),
    sa.Column('oktmo', sa.String(length=14), nullable=False),
    sa.Column('okato', sa.String(length=9), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('description_graduates_university')
    # ### end Alembic commands ###
